name: Build, Push and Deploy

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:
    name: Build and Test Flutter App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.4'  

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze || true

    - name: Run tests
      run: flutter test || true

    - name: Build Web (optional)
      run: flutter build web
