name: Build, Push and Deploy

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: ap-southeast-1
  ECR_REGISTRY: public.ecr.aws/c0t2e3x3/food-heaven
  IMAGE_TAG: latest

jobs:
  build:
    name: Build, Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.4'  

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze code
      run: flutter analyze || true

    - name: Run tests
      run: flutter test || true

    - name: Build Web
      run: flutter build web --release

    - name: Build Docker Image
      run: |
        docker build -t food-heaven:latest .

    - name: Tag Docker Image for ECR
      run: |
        docker tag food-heaven:latest $ECR_REGISTRY:$IMAGE_TAG

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Login to Amazon ECR Public
      run: |
        aws ecr-public get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin public.ecr.aws/c0t2e3x3

    - name: Push Docker image to ECR
      run: |
        docker push $ECR_REGISTRY:$IMAGE_TAG
